name: embed_example
description: "An example app for the oembed package."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_oembed:
    path: ../
  google_fonts: any
  url_launcher: ^6.3.1
  markdown: ^7.2.2
  markdown_widget: ^2.3.2+8
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.10+1
  flutter_quill: ^11.5.0
  visibility_detector: ^0.4.0+2
  flutter_cache_manager: ^3.4.1
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/logos/

