include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_specify_types: false
    - lines_longer_than_80_chars: false
